name: Azure Deployment

on:
  push:
    branches:
      - main

env:
  IMAGE_REACT: image_name_react
  IMAGE_NODE: image_name_node
  WEB_APP_NAME: havask.azurewebsites.net
  ACR_LOGIN_SERVER: havask.azurecr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        working-directory: ./front-end
        run: npm install

      - name: Build React.js Docker image
        run: docker build -t $ACR_LOGIN_SERVER/$IMAGE_REACT ./front-end

      - name: Build Node.js Docker image
        run: docker build -t $ACR_LOGIN_SERVER/$IMAGE_NODE ./back-end

      - name: Push React.js Docker image to Azure Container Registry
        run: |
          docker login $ACR_LOGIN_SERVER -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          docker push $ACR_LOGIN_SERVER/$IMAGE_REACT

      - name: Push Node.js Docker image to Azure Container Registry
        run: |
          docker login $ACR_LOGIN_SERVER -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          docker push $ACR_LOGIN_SERVER/$IMAGE_NODE

      - name: View debug log
        run: cat /root/.npm/_logs/2023-07-19T09_35_35_822Z-debug.log

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: $WEB_APP_NAME
          images: |
            $ACR_LOGIN_SERVER/$IMAGE_REACT:latest
            $ACR_LOGIN_SERVER/$IMAGE_NODE:latest
          run-from-package: false
          startup-command: |
            sh -c 'cd ./build; npm install; npm run start'
